create table "nextjs_session" ("id" integer GENERATED BY DEFAULT AS IDENTITY not null primary key, "expiresAt" timestamptz not null, "token" text not null unique, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null, "ipAddress" text, "userAgent" text, "userId" integer not null references "user_user" ("id") on delete cascade);

create table "nextjs_account" ("id" integer GENERATED BY DEFAULT AS IDENTITY not null primary key, "accountId" text not null, "providerId" text not null, "userId" integer not null references "user_user" ("id") on delete cascade, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" timestamptz, "refreshTokenExpiresAt" timestamptz, "scope" text, "password" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null);

create table "nextjs_verification" ("id" integer GENERATED BY DEFAULT AS IDENTITY not null primary key, "identifier" text not null, "value" text not null, "expiresAt" timestamptz not null, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);

create index "nextjs_session_userId_idx" on "nextjs_session" ("userId");

create index "nextjs_account_userId_idx" on "nextjs_account" ("userId");

create index "nextjs_verification_identifier_idx" on "nextjs_verification" ("identifier");